### PR TITLE
WIP Package as Flatpak

### PR DESCRIPTION
**Pull request by ljrk0**
Hello,

as per [1], I'd like to request to submit Threema Desktop to be distributed as a Flatpak app which can be installed in a Linux distribution-independent way, using an open build system for reproducible builds.  I've produced a submission-ready PR here [2] and only require your OK to submit it "officially".

However, there are some remaining open questions regarding maintaining of the packaging files:

1. As per [3] it is encouraged to submit the flatpak unrelated files such as `.desktop` and `.metadata.xml` upstream which I do as part of this PR.  If you do not want them tracked in your repo, I would keep them in the Flatpak repo instead.
2. The `.metadata.xml` I've created is using short descriptions copied from your website chosen by what I saw fit.  If you'd like to have a different description or summary, please tell me.
3. Further, I've entered my email as a metadata maintenance contact and would be fine doing that task.  However, if the metadata is to be tracked in your repo, it likely would be better to enter some contact of yours, but this isn't required.
4. Are there pre-made screenshots that could be linked from a metadata file or should I create my own?  These would be used in a graphical store frontend such as flathub.org or Gnome Software.  __For now I've created my own which you can find here: https://github.com/ljrk0/appstream-data/tree/main/ch.threema.threema-desktop__
5. The generated binary carries the name `Threema-linux-x64`.  In theory, Electron apps would be able to ship for `aarch64` as well.  Do you know what the generated binary name would be and/or accept patches to support packaging for those architectures?
6. Finally, `DEV_ENV=development` is set.  As far as I can tell this has no relevance on Linux but only macOS (it enables notarization).  I'd just like to double check that I didn't miss anything.

Thank you!

[1]: https://github.com/flathub/flathub/wiki/App-Submission#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer
[2]: https://github.com/flathub/flathub/pull/2630
[3]: https://github.com/flathub/flathub/wiki/App-Maintenance#acceptable-but-should-be-submitted-upstream

### CODE REVIEW

**Comment by ljrk0** [comment]
I've cleaned up the linked PR, it's basically ready to merge

**Comment by threema-danilo** [comment]
Hi @ljrk0, thank you for packaging Threema as a Flatpak! Sorry for the long time without a reply, we somehow missed your PR.

> only require your OK to submit it "officially"

This is OK from our side, as long as it's clear from the package description that the packaging is being done by the community, and not by Threema. We are currently trying to focus our efforts on the development of the new standalone Threema desktop client, and at this point in time do not want to maintain / support the Flatpak package as well. (Once the new version is released, this may change.) However, we are open to packages created by the community.

Regarding package metadata: We currently generate such metadata-files dynamically during our build process. I'm not sure if it makes sense from our side to provide a static metadata file, because we build multiple variants (i.e. the "regular" version of Threema, Threema Work, etc). However, we could probably provide you with the description strings and maybe also screenshots that could be used for packaging.

I'll discuss this with my colleagues and will let you know soon.

PS: We just pushed a new release, 1.1.0!

**Comment by ljrk0** [comment]
Hi @threema-danilo , thank you for coming back to me and thanks for the OK!

I will rework the package description to ensure that it is clear that the package itself is maintained by the community.  Going through the initial points:

1. I understand you don't have static metadata-files.  As far as the finally-installed metainfo.xml is concerned, generation of such files at build-time would be fine.  I'm not sure whether flathub itself expects static metainfo though and will research that.  If you could point me to the place where such metadata is generated (if this happens in this repo), and generating metainfo.xml at build-time, I'd write some code produce the format that flatpak expects from what you are using.  Otherwise, "official" description strings/screenshots would be great!
2. see above
3. If the metadata would be generated as part of the build-process it would perhaps still make sense to track it in this repository; otherwise, for static metadata, I would definitely put it in the actual flathub repo.  I assume filling my e-mail as contact would be okay then, though?
4. see (1)
5. I guess this falls under "focus on the new standalone client" :)
6. cleared up(?)

I'm looking forward to your reply and will update the flatpak to point to 1.1.0 as well as incorporate the description strings you may provide as it comes!  Looking forward to the new client thoguh :)

**Comment by threema-danilo** [comment]
We decided to provide a static metainfo.xml file and some screenshots in this repository. The desktop-file is created by the .deb and .rpm generators for Electron, but those should be fairly easy to add by hand when packaging (i.e. adding a static desktop file to the flatpak repo). I'm not sure a generic version provided by us makes sense here, because different distros or packaging methods might require special entrypoint-scripts, or things like that.

> 5. I guess this falls under "focus on the new standalone client" :)

Yeah, @threema-jarem might know more whether there are plans for aarch64-support.

> 6. Finally, `DEV_ENV=development` is set. As far as I can tell this has no relevance on Linux but only macOS (it enables notarization). I'd just like to double check that I didn't miss anything.

Yes, I think that's the case. Maybe @threema-jarem can confirm this?

**Comment by ghost** [comment]
> > 5. I guess this falls under "focus on the new standalone client" :)

> Yeah, @threema-jarem might know more whether there are plans for aarch64-support.

Yes, there are no plans for adding arm64 support to the debian package. We could accept a pull request for supporting generating a build, but without providing a prebuilt package on our website.

Adding support for arm64 should be fairly straightforward. First one would have to add a second architecture for the debian package here: https://github.com/threema-ch/threema-web-electron/blob/63b04a164db129c80e58048ffa2304cc9f0af45f/app/package.json#L177

and then process it in `package-deb.js` by looping over all architectures. This should give you something like `threema-alpha_1.0.13~alpha_arm64.deb`.

> 6. Finally, DEV_ENV=development is set. As far as I can tell this has no relevance on Linux but only macOS (it enables notarization). I'd just like to double check that I didn't miss anything.

Yes, that is currently the case. But I wouldn't want to promise that this will never change in the future.

**Comment by threema-danilo** [comment]
@ljrk0 the `develop` branch now contains additional metadata: https://github.com/threema-ch/threema-web-electron/commit/0c0f22f9f65e7cdaf070dc2cc67a4b6542641195

Do you need anything else?

**Comment by ljrk0** [comment]
> @ljrk0 the `develop` branch now contains additional metadata: [0c0f22f](https://github.com/threema-ch/threema-web-electron/commit/0c0f22f9f65e7cdaf070dc2cc67a4b6542641195)
> 
> Do you need anything else?

Lovely!  No, I don't think I need anything else.  I'll look into generating the .desktop in some way perhaps from your code but that's it.  With all that in place building this via Flathub should work fine.  However, I probably will need to carry some patches for NPM to change it to pull using https instead of ssh as the latter requires authentication within the CI.  But that's a minor thing I can hopefully even contribute back into this repo after I'm done.

**Comment by threema-danilo** [comment]
Great! Let us know if you need anything else.

Please note, in the metainfo XML we changed the ID from `ch.threema.threema-desktop` to `ch.threema.threema-web-desktop`. The reason is that there will probably be an official Flatpak for Threema Desktop 2.0, which should have a separate ID so that the two versions could be installed side-by-side (2.0 will be a complete re-implementation with different architecture).

**Comment by ghost** [comment]
closing due to inactivity

**Pull request closed without merging**
